### PR TITLE
Update Cloudberry Backup version

### PR DESCRIPTION
**Pull request by fergbrain**
Update to use the latest version of Cloudberry Backup

### CODE REVIEW

**Comment by jlesage** [comment]
Hello,
Thanks for this!  But I'm waiting for the next version to be released, because this version as a known issue that is causing the UI to constantly disconnect from the backup engine...  The CloudBerry support team told me that they are working on a fix.

**Comment by fergbrain** [comment]
Understood. Do you know if the bug impacts just the GUI or the web interface as well?

**Comment by jlesage** [comment]
I don't know, I didn't tried this version with the web interface yet.

**Comment by fergbrain** [comment]
For what it's worth, I've not had any issues with either the GUI or web app thus far whilst running v2.7.0.28.

**Comment by davosian** [comment]
Version 2.8.0.35 has been released. Do you know if it contains the expected fix?

**Comment by fergbrain** [comment]
The notice on their site only lists updates, nothing about bug fixes. Having said that, I've had no issues running the docker container with v2.7.0.28 and now with v2.8.0.35 (which I've updated the patch to use).

**Comment by jlesage** [comment]
Sorry I didn't see that you updated the PR before doing my changes...

**Comment by jlesage** [comment]
For me the issue is not fixed with the 2.8 version.  But since you don't have the issue, I've made a release with this version.

**Pull request closed without merging**
